const express=require('express');const session=require('express-session');const PgSession=require('connect-pg-simple')(session);const {Pool}=require('pg');const bcrypt=require('bcryptjs');
const app=express();const PORT=process.env.PORT||3000;const DEMO_OPEN=process.env.DEMO_OPEN==='true';
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL&&!process.env.DATABASE_URL.includes('localhost')?{rejectUnauthorized:false}:false});
app.use(express.json({limit:'1mb'}));app.use(express.urlencoded({extended:true}));
app.use(session({store:process.env.DATABASE_URL?new PgSession({pool,tableName:'user_sessions',createTableIfMissing:true}):undefined,secret:process.env.SESSION_SECRET||'change-this-secret',resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:1000*60*60*12}}));
app.use(express.static('public'));
async function q(text,params=[]){return pool.query(text,params)}
async function init(){await q(require('fs').readFileSync(__dirname+'/schema.sql','utf8'));const r=await q('SELECT id FROM users WHERE username=$1',['admin']);if(!r.rowCount){const hash=await bcrypt.hash('1234',12);await q('INSERT INTO users(username,password_hash,display_name,role) VALUES($1,$2,$3,$4)',['admin',hash,'Administrador','admin']);}}
function user(req){if(req.session.user)return req.session.user; if(DEMO_OPEN)return {id:1,username:'admin',display_name:'Administrador',role:'admin'};return null}
function auth(req,res,next){const u=user(req);if(!u)return res.status(401).json({error:'Sesión requerida'});req.user=u;next()}
function admin(req,res,next){if(req.user.role!=='admin')return res.status(403).json({error:'Solo el administrador puede realizar esta acción'});next()}
function supervisorOrAdmin(req,res,next){if(!['admin','supervisor'].includes(req.user.role))return res.status(403).json({error:'Permiso insuficiente'});next()}
async function audit(actor,action,entity=null,entityId=null,detail={}){try{await q('INSERT INTO audit_log(actor_id,action,entity,entity_id,detail) VALUES($1,$2,$3,$4,$5)',[actor,action,entity,entityId,JSON.stringify(detail)])}catch(e){console.error('audit',e.message)}}
function scopeClient(c,u){return u.role==='admin'||(u.role==='supervisor'&&c.assigned_cobrador_id&&true)||(u.role==='cobrador'&&c.assigned_cobrador_id===u.id)}
app.get('/api/health',async(req,res)=>{try{await q('SELECT 1');res.json({ok:true,mode:DEMO_OPEN?'open-demo':'private'})}catch(e){res.status(503).json({ok:false,error:e.message})}});
app.get('/api/me',(req,res)=>res.json({user:user(req),demo:DEMO_OPEN}));
app.post('/api/login',async(req,res)=>{try{const {username,password}=req.body;const r=await q('SELECT * FROM users WHERE username=$1 AND active=true',[username]);if(!r.rowCount||!await bcrypt.compare(password,r.rows[0].password_hash))return res.status(401).json({error:'Usuario o contraseña incorrectos'});const u=r.rows[0];req.session.user={id:u.id,username:u.username,display_name:u.display_name,role:u.role,supervisor_id:u.supervisor_id};res.json({user:req.session.user})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/logout',(req,res)=>req.session.destroy(()=>res.json({ok:true})));
app.get('/api/dashboard',auth,async(req,res)=>{try{const [c,l,p,exp,cash]=await Promise.all([q('SELECT COUNT(*) n FROM clients'),q("SELECT COUNT(*) n FROM loans WHERE status='Activo'"),q('SELECT COALESCE(SUM(amount),0) n FROM payments'),q('SELECT COALESCE(SUM(amount),0) n FROM expenses'),q("SELECT COALESCE(SUM(CASE WHEN type IN ('INYECCION','COBRO','AJUSTE') THEN amount ELSE -amount END),0) n FROM cash_movements")]);let where='',params=[];if(req.user.role==='cobrador'){where=' AND l.cobrador_id=$1';params=[req.user.id]}else if(req.user.role==='supervisor'){where=' AND u.supervisor_id=$1';params=[req.user.id]};const pend=await q(`SELECT COUNT(*) n FROM installments i JOIN loans l ON l.id=i.loan_id LEFT JOIN users u ON u.id=l.cobrador_id WHERE i.due_date<=CURRENT_DATE AND l.status='Activo' ${where}`,params);res.json({clients:+c.rows[0].n,activeLoans:+l.rows[0].n,totalCollected:+p.rows[0].n,totalExpenses:+exp.rows[0].n,systemCash:+cash.rows[0].n,pending:+pend.rows[0].n})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/users',auth,admin,async(req,res)=>{const r=await q("SELECT id,username,display_name,role,supervisor_id,active,created_at FROM users ORDER BY role,display_name");res.json(r.rows)});
app.post('/api/users',auth,admin,async(req,res)=>{try{const {username,password,displayName,role,supervisorId}=req.body;if(!username||!password||!displayName||!['supervisor','cobrador','admin'].includes(role))return res.status(400).json({error:'Datos incompletos'});if(role==='cobrador'&&!supervisorId)return res.status(400).json({error:'Asigna un supervisor al cobrador'});const hash=await bcrypt.hash(password,12);const r=await q('INSERT INTO users(username,password_hash,display_name,role,supervisor_id) VALUES($1,$2,$3,$4,$5) RETURNING id,username,display_name,role,supervisor_id',[username,hash,displayName,role,supervisorId||null]);if(role==='cobrador')await q('INSERT INTO audit_log(actor_id,action,entity,entity_id,detail) VALUES($1,$2,$3,$4,$5)',[req.user.id,'CREAR_USUARIO','users',r.rows[0].id,JSON.stringify({role})]);res.json(r.rows[0])}catch(e){res.status(400).json({error:e.code==='23505'?'Ese usuario ya existe':e.message})}});
app.get('/api/clients',auth,async(req,res)=>{let sql='SELECT c.*,u.display_name cobrador FROM clients c LEFT JOIN users u ON u.id=c.assigned_cobrador_id';let p=[];if(req.user.role==='cobrador'){sql+=' WHERE c.assigned_cobrador_id=$1';p=[req.user.id]}else if(req.user.role==='supervisor'){sql+=' WHERE u.supervisor_id=$1';p=[req.user.id]}sql+=' ORDER BY c.name';res.json((await q(sql,p)).rows)});
app.post('/api/clients',auth,async(req,res)=>{try{const {name,phone,address,business,latitude,longitude,cobradorId}=req.body;if(!name)return res.status(400).json({error:'Nombre requerido'});let cid=cobradorId||null;if(req.user.role==='cobrador')cid=req.user.id; if(req.user.role==='supervisor'&&cid){const z=await q('SELECT id FROM users WHERE id=$1 AND supervisor_id=$2 AND role=\'cobrador\'',[cid,req.user.id]);if(!z.rowCount)return res.status(403).json({error:'Cobrador no pertenece a tu equipo'})}const r=await q('INSERT INTO clients(name,phone,address,business,latitude,longitude,assigned_cobrador_id) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *',[name,phone||null,address||null,business||null,latitude||null,longitude||null,cid]);await audit(req.user.id,'CREAR_CLIENTE','clients',r.rows[0].id,{name});res.json(r.rows[0])}catch(e){res.status(400).json({error:e.message})}});
app.get('/api/loans',auth,async(req,res)=>{let sql=`SELECT l.*,c.name client_name,u.display_name cobrador,COALESCE((SELECT SUM(amount) FROM payments p WHERE p.loan_id=l.id),0) paid FROM loans l JOIN clients c ON c.id=l.client_id LEFT JOIN users u ON u.id=l.cobrador_id`;let p=[];if(req.user.role==='cobrador'){sql+=' WHERE l.cobrador_id=$1';p=[req.user.id]}else if(req.user.role==='supervisor'){sql+=' WHERE u.supervisor_id=$1';p=[req.user.id]}sql+=' ORDER BY l.created_at DESC';res.json((await q(sql,p)).rows)});
app.post('/api/loans',auth,async(req,res)=>{const clientId=+req.body.clientId;let cobradorId=req.body.cobradorId?+req.body.cobradorId:null;if(req.user.role==='cobrador')cobradorId=req.user.id;try{const c=await q('SELECT * FROM clients WHERE id=$1',[clientId]);if(!c.rowCount)return res.status(404).json({error:'Cliente no encontrado'});if(req.user.role==='cobrador'&&c.rows[0].assigned_cobrador_id!==req.user.id)return res.status(403).json({error:'Cliente no asignado'});const amount=Number(req.body.amount),interest=Number(req.body.interest||0),count=+req.body.installmentsCount,frequency=req.body.frequency,start=req.body.startDate;if(!(amount>0&&count>0&&['Diaria','Semanal','Mensual'].includes(frequency)&&start))return res.status(400).json({error:'Datos del préstamo inválidos'});const total=amount+interest,base=Math.floor(total/count*100)/100;const client=await pool.connect();try{await client.query('BEGIN');const lr=await client.query('INSERT INTO loans(client_id,cobrador_id,amount,interest,total,frequency,installments_count,installment_amount,start_date) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *',[clientId,cobradorId,amount,interest,total,frequency,count,base,start]);for(let n=1;n<=count;n++){const d=new Date(start+'T00:00:00Z');if(frequency==='Diaria')d.setUTCDate(d.getUTCDate()+n-1);if(frequency==='Semanal')d.setUTCDate(d.getUTCDate()+7*(n-1));if(frequency==='Mensual')d.setUTCMonth(d.getUTCMonth()+n-1);const amt=n===count?Number((total-base*(count-1)).toFixed(2)):base;await client.query('INSERT INTO installments(loan_id,number,due_date,amount) VALUES($1,$2,$3,$4)',[lr.rows[0].id,n,d.toISOString().slice(0,10),amt])}await client.query('COMMIT');await audit(req.user.id,'CREAR_PRESTAMO','loans',lr.rows[0].id,{clientId,total,count,frequency});res.json(lr.rows[0])}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}}catch(e){res.status(400).json({error:e.message})}});
app.get('/api/collection',auth,async(req,res)=>{let sql=`SELECT i.*,l.client_id,l.cobrador_id,c.name client_name,c.phone,c.address,l.frequency,l.installment_amount,COALESCE((SELECT SUM(amount) FROM payments p WHERE p.installment_id=i.id),0) paid FROM installments i JOIN loans l ON l.id=i.loan_id JOIN clients c ON c.id=l.client_id LEFT JOIN users u ON u.id=l.cobrador_id WHERE l.status='Activo'`;let p=[];if(req.user.role==='cobrador'){sql+=' AND l.cobrador_id=$1';p=[req.user.id]}else if(req.user.role==='supervisor'){sql+=' AND u.supervisor_id=$1';p=[req.user.id]}sql+=' ORDER BY i.due_date,i.number';res.json((await q(sql,p)).rows)});
app.post('/api/payments',auth,async(req,res)=>{const amount=Number(req.body.amount),installmentId=+req.body.installmentId;if(!(amount>0&&installmentId))return res.status(400).json({error:'Monto y cuota son obligatorios'});const c=await pool.connect();try{await c.query('BEGIN');const ir=await c.query(`SELECT i.*,l.cobrador_id,l.client_id FROM installments i JOIN loans l ON l.id=i.loan_id WHERE i.id=$1 FOR UPDATE`,[installmentId]);if(!ir.rowCount)throw Error('Cuota no encontrada');const i=ir.rows[0];if(req.user.role==='cobrador'&&i.cobrador_id!==req.user.id)throw Error('Cuota no asignada');const pr=await c.query('SELECT COALESCE(SUM(amount),0) paid FROM payments WHERE installment_id=$1',[installmentId]);const remaining=Number(i.amount)-Number(pr.rows[0].paid);if(amount>remaining+0.001)throw Error('El pago supera el saldo de la cuota');const pay=await c.query('INSERT INTO payments(loan_id,installment_id,amount,collector_id,note) VALUES($1,$2,$3,$4,$5) RETURNING *',[i.loan_id,installmentId,amount,req.user.id,req.body.note||null]);await c.query('INSERT INTO cash_movements(user_id,type,amount,payment_id,note,created_by) VALUES($1,\'COBRO\',$2,$3,$4,$5)',[i.cobrador_id||req.user.id,amount,pay.rows[0].id,`Cobro cliente ${i.client_id}`,req.user.id]);await c.query('COMMIT');await audit(req.user.id,'REGISTRAR_COBRO','payments',pay.rows[0].id,{installmentId,amount});res.json(pay.rows[0])}catch(e){await c.query('ROLLBACK');res.status(400).json({error:e.message})}finally{c.release()}});
app.get('/api/cash',auth,async(req,res)=>{let uid=req.query.userId?+req.query.userId:req.user.id;if(req.user.role!=='admin')uid=req.user.id;const u=await q('SELECT id,display_name,role FROM users WHERE id=$1',[uid]);if(!u.rowCount)return res.status(404).json({error:'Usuario no encontrado'});const m=await q(`SELECT cm.*,p.id payment_id,e.description expense_description,creator.display_name created_by_name FROM cash_movements cm LEFT JOIN payments p ON p.id=cm.payment_id LEFT JOIN expenses e ON e.id=cm.expense_id LEFT JOIN users creator ON creator.id=cm.created_by WHERE cm.user_id=$1 ORDER BY cm.created_at DESC`,[uid]);const balance=m.rows.reduce((s,x)=>s+(['INYECCION','COBRO','AJUSTE'].includes(x.type)?Number(x.amount):-Number(x.amount)),0);res.json({user:u.rows[0],balance,movements:m.rows})});
app.get('/api/cash/users',auth,async(req,res)=>{if(req.user.role!=='admin')return res.status(403).json({error:'Solo administrador'});res.json((await q("SELECT id,display_name,username,role FROM users WHERE role='cobrador' AND active=true ORDER BY display_name")).rows)});
app.post('/api/cash/inject',auth,admin,async(req,res)=>{const userId=+req.body.userId,amount=Number(req.body.amount);if(!(userId&&amount>0))return res.status(400).json({error:'Cobrador y monto son obligatorios'});const u=await q("SELECT id FROM users WHERE id=$1 AND role='cobrador' AND active=true",[userId]);if(!u.rowCount)return res.status(400).json({error:'Cobrador inválido'});const r=await q('INSERT INTO cash_movements(user_id,type,amount,note,created_by) VALUES($1,\'INYECCION\',$2,$3,$4) RETURNING *',[userId,amount,req.body.note||'Inyección de capital',req.user.id]);await audit(req.user.id,'INYECCION_CAJA','cash_movements',r.rows[0].id,{userId,amount});res.json(r.rows[0])});
app.post('/api/cash/withdraw',auth,admin,async(req,res)=>{const userId=+req.body.userId,amount=Number(req.body.amount);if(!(userId&&amount>0))return res.status(400).json({error:'Datos inválidos'});const bal=await q("SELECT COALESCE(SUM(CASE WHEN type IN ('INYECCION','COBRO','AJUSTE') THEN amount ELSE -amount END),0) balance FROM cash_movements WHERE user_id=$1",[userId]);if(amount>Number(bal.rows[0].balance))return res.status(400).json({error:'El retiro supera el saldo de la caja'});const r=await q('INSERT INTO cash_movements(user_id,type,amount,note,created_by) VALUES($1,\'RETIRO\',$2,$3,$4) RETURNING *',[userId,amount,req.body.note||'Retiro/entrega al administrador',req.user.id]);await audit(req.user.id,'RETIRO_CAJA','cash_movements',r.rows[0].id,{userId,amount});res.json(r.rows[0])});
app.post('/api/expenses',auth,async(req,res)=>{const amount=Number(req.body.amount);if(!(amount>0&&req.body.description))return res.status(400).json({error:'Datos inválidos'});const collector=req.user.role==='cobrador'?req.user.id:(req.body.userId?+req.body.userId:null);if(!collector)return res.status(400).json({error:'Selecciona la caja del cobrador'});const bal=await q("SELECT COALESCE(SUM(CASE WHEN type IN ('INYECCION','COBRO','AJUSTE') THEN amount ELSE -amount END),0) balance FROM cash_movements WHERE user_id=$1",[collector]);if(req.user.role!=='admin'&&amount>Number(bal.rows[0].balance))return res.status(400).json({error:'Saldo insuficiente en la caja'});const c=await pool.connect();try{await c.query('BEGIN');const e=await c.query('INSERT INTO expenses(amount,description,collector_id,created_by) VALUES($1,$2,$3,$4) RETURNING *',[amount,req.body.description,collector,req.user.id]);await c.query('INSERT INTO cash_movements(user_id,type,amount,expense_id,note,created_by) VALUES($1,\'GASTO\',$2,$3,$4,$5)',[collector,amount,e.rows[0].id,req.body.description,req.user.id]);await c.query('COMMIT');await audit(req.user.id,'REGISTRAR_GASTO','expenses',e.rows[0].id,{amount,collector});res.json(e.rows[0])}catch(e){await c.query('ROLLBACK');res.status(400).json({error:e.message})}finally{c.release()}});
app.get('/api/reports/summary',auth,async(req,res)=>{const p=[];let where='';if(req.user.role==='cobrador'){where=' AND p.collector_id=$1';p.push(req.user.id)}else if(req.user.role==='supervisor'){where=' AND u.supervisor_id=$1';p.push(req.user.id)}const r=await q(`SELECT DATE(p.paid_at) day,COALESCE(SUM(p.amount),0) collected,COUNT(*) payments FROM payments p LEFT JOIN users u ON u.id=p.collector_id WHERE p.paid_at>=CURRENT_DATE-INTERVAL '30 days' ${where} GROUP BY DATE(p.paid_at) ORDER BY day DESC`,p);res.json(r.rows)});
app.get('/{*splat}',(req,res)=>res.sendFile(__dirname+'/public/index.html'));
init().then(()=>app.listen(PORT,'0.0.0.0',()=>console.log(`Control Cobranza on ${PORT}`))).catch(e=>{console.error(e);process.exit(1)});
